### ISSUE TITLE
Some suggestions for improvements

### ISSUE THREAD

**Issue by PetarMetodiev** [rgroli/other.nvim#1]
First of all - thanks for creating this plugin. It is something I find very useful in my workflow as a FE developer.
I noticed it is a young project and thought I could give some suggestions for further development. I know that these may be only relevant to me, but hey it may be worth a shot.
To give some context - as a FE developer(React) I constantly have to switch between `.tsx` and `.scss` files. I have an issue though - I am working on a legacy code base and sometimes the styles file is `.css`(and not `.scss`). With that in mind here are my suggestions for further development:

- Allow for the target to be regex. This would help when I just want the "other" file to be either `.css` or `.scss`. If both `.css` and `.scss` are present - show a file picker.
 
- By default if the "other" file is not present it is being silently created. While this seems convenient, I guess having the option to disable this behaviour in the `setup` function would be nice. For example if I have the plugin configured to not create the missing "other" file I would expect to see (ideally) a floating window which tells me the "other" file does not exist and asking me if I want to create it.

Thanks again for creating this plugin and keep up the good work!

**Comment by rgroli** [comment]
Thank you for your suggestions!

To address your main-issues, I introduced glob-like pattern matching in the target section of the mapping. So you can now do something like this:
```lua 
require("other-nvim").setup({
   -- [...]
    mappings = {
    	{
            pattern = "/src/(.*)/.*.js$",
            target = "/src/%1/\\(*.css\\|*.scss\\)",
    	},
   -- [...]
```
Beware that the glob-part needs escaping with double-backslashes in the "glob-part".

Also the other issue that  files are silently created when not existent is resolved. Due to some internal restructuring the plugin will no longer open a buffer of non-existing files. Which is actually better. Thanks for the hint!
